[project]
name = "veronique"
version = "0.2.0"
description = "Private graph DB / social network"
authors = [
  {name = "L3viathan", email="git@l3vi.de"},
]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
  "sanic",
  "markdown-it-py[linkify]",
  "phonenumbers",
  "pycountry>=24.6.1",
]
[dependency-groups]
dev = [
  "mkdocs",
  "ruff",
  "sanic-testing",
  "pytest",
  "pytest-asyncio",
]
[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[project.urls]
Repository = "https://github.com/L3viathan/veronique"

[project.scripts]
veronique-bootstrap = "veronique.bootstrap:cli"

[tool.uv.build-backend]
module-name = "veronique"
module-root = ""
source-exclude = ["test/**"]
data = { data = "data" }

[tool.ruff.lint]
ignore = [
  "DTZ011",  # datetime without tz: UTC everywhere (without needing tz)
  "DTZ005",  # same here
  "B020",  # loop variable overrides iterable: I do that intentionally
  "SIM103",  # return condition directly; not always more readable
]
