from datetime import timedelta


SESSION_REFRESH_AFTER = timedelta(days=7)
SESSION_MAX_AGE = timedelta(days=30)

CLAIM_DATA_CACHE_TIME = timedelta(minutes=5)

SEARCH_AVGDL_CACHE_TIME = timedelta(hours=1)
SEARCH_AVGDL_FALLBACK = 15  # just some semi-realistic value
SEARCH_DEFAULT_K1 = 0.25
SEARCH_DEFAULT_B = 0.75
SEARCH_DEFAULT_N = 3

SECURITY_KEY_SIZE = 16
SECURITY_SALT_SIZE = 16
SECURITY_PBKDF2_HMAC_ROUNDS = 500_000

INDEX_DEFAULT_TYPE = "recent_events"
INDEX_DEFAULT_DAYS_AHEAD = 7
INDEX_DEFAULT_DAYS_BACK = 3
INDEX_DEFAULT_RECENT_EVENTS_MOD = 1

DEFAULT_PHONE_REGION = "DE"
DEFAULT_PAGE_SIZE = 20
DEFAULT_APP_NAME = "Véronique"
