name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Install uv
        uses: astral-sh/setup-uv@main
      - name: Set up Python
        run: uv python install
      - name: Install project
        run: uv sync --all-extras --dev
      - name: Test
        run: uv run pytest
      - name: Lint
        run: uv run ruff check
    permissions:
      contents: read
